name: BungeePortals
version: 1.1
description: Create portals of any shape or size with WorldEdit, for BungeeCord.
author: YoFuzzy3
main: com.fuzzoland.bungeeportals.BungeePortals
dev-url: http://www.spigotmc.org/resources/bungeeportals.19/
softdepend: [WorldEdit]

commands:
  bungeeportals:
    aliases: [bportals]
    description: Command to manage BungeeCord server portals.
permissions:
  bungeeportals.command.bportals:
    description: Allowed to access the command /BPortals.
    default: op
  bungeebortals.portal.*:
    description: Access to all portals.
    default: true